### ISSUE TITLE
[BUG] Export settings errors out if Fog Manager is enabled

### ISSUE THREAD

**Issue by esheyw** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#26]
**Describe the bug**
If you've got FCE and [Fog Manager](https://gitlab.com/tiwato/fogmanager) both enabled, even if those are the only two modules active, 'export settings' errors as such: 
```
Uncaught TypeError: Cannot read properties of null (reading '0')
    at helpers.mjs:104:57
    at Array.reduce (<anonymous>)
    at diffObject (helpers.mjs:102:29)
    at core.js:398:38
    at Array.filter (<anonymous>)
    at Function.exportGameSettings (core.js:394:10)
    at Object.callback (module.js:38:16)
    at HTMLLIElement.<anonymous> (foundry.js:43944:14)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at HTMLLIElement.v.handle (jquery.min.js:2:41048)
```

Foundry, FCE, and Fog Manager all up to date.

**Comment by sneat** [comment]
Have fixed this in v2.1.2, thank you.
